name: transaction-classification-bot


services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
