import type { Metadata } from "next";
import "./globals.css";
import SignOutButton from "@/components/signout-button";

export const metadata: Metadata = {
  title: "Transaction Classification Bot",
  description: "Generated by CST students",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 py-4 flex justify-between items-center px-6 sticky top-0 z-50">
          <div className="text-white">{metadata.title as React.ReactNode}</div>
          <SignOutButton />
        </nav>
        {children}
      </body>
    </html>
  );
}
