name: Prettier and Eslint Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          token: ${{ secrets.ACTIONS_TOKEN }}
        
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit # This ensures pre-commit is 
      
      - name: Run pre-commit Hooks
        run: pre-commit run --all-files # Runs the precommit hooks on all files

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pre-commit formatting changes
          branch: ${{ github.head_ref }}