name: Playwright Tests

on:
  push:
    branches: [main, feature/codecov]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      working-directory: ./playwright-tests
      run: npm install
    - name: Install dependancies
      working-directory: ./backend
      run: pip install coverage

    - name: Install Playwright Browsers
      working-directory: ./playwright-tests
      run: npx playwright install --with-deps

    - name: Run frontend and backend tests with coverage
      run: |
        cd playwright-tests && npm run test:playwright
        cd ../backend && coverage run -m pytest
        coverage lcov -o ../playwright-tests/coverage/python-lcov.info

    - name: Combine coverage reports
      run: |
        cd playwright-tests/coverage
        lcov -a lcov.info -a python-lcov.info -o combined-lcov.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: playwright-tests/coverage/combined-lcov.info
        fail_ci_if_error: true
