name: Playwright Tests

on:
  push:
    branches: [main, feature/codecov]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      working-directory: ./playwright-tests
      run: npm install

    - name: Install Playwright Browsers
      working-directory: ./playwright-tests
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./playwright-tests
      run: npx nyc --reporter=lcov --reporter=text npx playwright test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./playwright-tests/coverage/lcov.info
        fail_ci_if_error: true
